#!/usr/bin/env bash
set -e
shopt -s extglob

CONFIG="${HOME}/.gportal-readlog.conf"

if [ ! -f "${CONFIG}" ]; then
	echo "${CONFIG} not found, aborting."
	exit 1
fi

source "${CONFIG}"

x=1
while getopts "dflth" opt; do
	case "$opt" in
		d) debug="true";;
		f) usefull="true";;
		l) uselocal="true";;
		t) today="true";;
		h|\?) printf 'Usage: %s [-d] [-f] [-l] START_TIME[s|m|h|d|e]
	-d	Print deaths as they occur
	-f	Use the full log instead of current system log
	-l	Use the log file found in LOCALPATH
	-t	Only show logs since 00:00:00 today

START_TIME can be specified with an optional suffix for:
	(s)econds
	(m)inutes
	(h)ours
	(d)ays
	seconds since the (e)poch

Values without a suffix assume "d", unless the value is >9999, in which case "e" is assumed.\n\n' "$(basename "$0")"; exit 0;;
	esac
	x=$OPTIND
done
shift $(($x-1))

if [ ! "$uselocal" -a -z "$CURLURL" ]; then
	echo "CURLURL is required, but not defined, exiting"
	exit 1
elif [ ! "$uselocal" -a -z "$FULLCURLURL" ]; then
	echo "FULLCURLURL is required, but not defined, exiting"
	exit 1
fi

if [ "$today" ]; then
	# get current time
	printf -v t '%(%-H %-M %-S)T'
	# as an array
	t=( $t )
	now=$EPOCHSECONDS
	(( now -= t[2] , now -= t[1] * 60 , now -= t * 3600 ))
	starttime="$now"
fi

if [[ "$1" =~ ^[0-9]+[smhde]*$ ]]; then
	timevalue="${1%[smhde]}"
	suffix="${1##+([0-9])}"

	if [ ! "$suffix" -a "$timevalue" -gt 9999 ]; then
		suffix="e"
	fi

	case "$suffix" in
		s) multiplier=1;;
		m) multiplier=60;;
		h) multiplier=3600;;
		d) multiplier=86400;;
		e) starttime="${timevalue}";;
		# assume days if not specified
		*) multiplier=86400;;
	esac

	if [ ! "$starttime" ]; then
		starttime=$((EPOCHSECONDS - multiplier * timevalue))
	fi
fi

main() {
hash gawk 2> /dev/null || { printf 'gawk is required but unavailable, aborting\n' >&2 && exit 1; }
hash mktemp 2> /dev/null || { printf 'mktemp is required but unavailable, aborting\n' >&2 && exit 1; }

loadawk || { printf 'Unable to create temp file, aborting\n' >&2 && exit 1; }

set -o pipefail
loadlog
if ! rungawk; then
	usefull="true"
	starttime=$((EPOCHSECONDS - 7 * 86400))
	loadlog
	rungawk
fi
}

rungawk() {
	gawk -v "debug=$debug" -v "starttime=$starttime" -f "${tempfile}" <<< "$returndata"
}

loadlog() {
	if [ "$usefull" ]; then
		CURLURL="$FULLCURLURL"
	elif [ "$uselocal" ]; then
		datasource="$LOCALPATH"
	fi

	datasource="$(cut -f3 -d/ <<< "$CURLURL" | cut -f2 -d@ | cut -f1 -d:)"

	printf 'Reading data from %s...\n' "$datasource"

	if [ "$uselocal" ]; then
		if [ -f "$LOCALPATH" ]; then
			returndata=$(<$LOCALPATH)
		else
			printf 'LOCALPATH required, but not defined, aborting\n'
			exit 1
		fi
	else
		returndata="$(curl --connect-timeout 2 -s "$CURLURL")" || { printf 'Unable to connect to %s, aborting\n' "$CURLURL" >&2 && exit 1; }
	fi
}

cleanup() {
	rm -f "${tempfile}"
}

loadawk() {
	tempfile="$(mktemp -t readlog.XXXX)"
	cat - > "${tempfile}" <<'EndOfAwk'
